check static "host" parameters contain valid hostname
Domain-Connect/dc-template-linter pull request #14
Opened 2024-11-08 10:01 UTC by kerolasa

Reported-by: Pawel Kowalik <kowalik@denic.de>
Fixes: https://github.com/Domain-Connect/dc-template-linter/issues/13

2024-11-08 17:12 UTC, thoag-godaddy commented
I think this is a result of the discussion in https://github.com/Domain-Connect/Templates/pull/568
In that PR it was the rfc import of "sub domain" that made the underscores invalid for the dkim selector.

In my research there is no indication that a DNS name containing underscores beyond position 1 is invalid. It is true that host names cannot have said underscores, but not necessarily true for a domain name (rfc1034).

2024-11-09 23:05 UTC, pawel-kow requested changes

2024-11-09 23:05 UTC, pawel-kow commented on internal/dctl.go
> +	DCTL1025: "use of underscore in detected in a host: element",
One in too much

2024-11-12 14:11 UTC, kerolasa commented
@thoag-godaddy I agree. Underscore is merely something one should review more carefully. I updated the change to lower the messaging level from Warning to Info, and added a bit of text to commit message telling it's not end of the world if underscore is detected -- one should just think about it before moving forward.

2024-11-13 09:39 UTC, merged